name: Upload Node.js 10 and 12 tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: windows-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Actions GH Release
        uses: softprops/action-gh-release@v1
      - name: list
        run: cd "C:\hostedtoolcache\windows"; ls;
